title: CSCI 1570
description: CSCI 1570 Course Website
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://csci1570.github.io
aux_links:
  Ed:
    - https://csci1570.github.io
  Gradescope:
    - https://csci1570.github.io

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
