title: CSCI 1570
tagline: Design and Analysis of Algorithms
description: Brown University, Fall 2026
author: Claire Mathieu and Manas Korimilli
theme: just-the-docs

url: https://csci1570.github.io
edstem_url: &edstem_url "https://csci1570.github.io"
gradescope_url: &gradescope_url "https://csci1570.github.io"
aux_links:
  Ed:
    - *edstem_url
  Gradescope:
    - *gradescope_url

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
